Duplicate pages, connection, components
mui/mui-toolpad pull request #1210
Opened 2022-10-25 09:05 UTC by Janpot

WIP

2022-10-26 13:28 UTC, Janpot commented
> Could you just clarify a bit more why fragments are needed?

To be able to navigate to the page after duplicating it we need access to the id of duplicated node. To get access to this id I split the duplication process into two: `cloneFragment`, which gives you a cloned dom with the root element being the id that we want. and then `addFragment` which inserts the cloned nodes. For when we add cut/paste we can add a `getFragment` to get a segment from the dom, followed by a `removeNode` and a `addFragment`. For this we will also need to be able to specify parent index, and not just paste at the end.

2022-10-26 21:19 UTC, apedroferreira requested changes
Looks good, I think fragments will be useful!
I found a possible issue, let me know if it makes sense.

2022-10-26 21:19 UTC, apedroferreira commented on test/integration/duplication/index.spec.ts
> +    await editorModel.openHierarchyMenu('connection1');
Would it be worth testing that the new menu item is added after duplicating, and removed after deleting?

2022-10-27 05:39 UTC, Janpot commented on packages/toolpad-app/src/toolpad/AppEditor/HierarchyExplorer/index.tsx
> +      const fragment = appDom.cloneFragment(dom, node.id);
https://github.com/mui/mui-toolpad/pull/1210#issuecomment-1292036450

2022-10-27 07:46 UTC, Janpot commented
> I tried duplicating "page1" and it seems that the suggested name is "page11" instead of "page2"

👍 My reasoning was that we shouldn't assume the number at the end of a name was added by us. And we should just always restart numbering. But that is probably less intuitive. I changed it to always increment if the name already starts with a number.

2022-10-27 11:20 UTC, apedroferreira approved these changes
Looks good, thanks for the changes!

2022-10-27 11:20 UTC, merged