Be more accepting of select options
mui/mui-toolpad pull request #1604
Opened 2023-01-27 16:41 UTC by Janpot

Make sure we always show something, even if the options array contains numbers, or `undefined`

2023-01-30 16:08 UTC, apedroferreira requested changes
Works well, just added some thoughts about the tests! Feel free to disagree.

2023-02-01 10:15 UTC, Janpot commented on test/integration/components/index.spec.ts
> +  const optionsSelect = frame.getByRole('button', { name: /select with options/ });
Maybe, I'm sort of avoiding splitting tests too much as to keep the footprint down. The whole test with setup and page load takes about 2/3 seconds. While just interacting with this select takes an order of magnitude less.
But perhaps it is sensible to add one test per component

2023-02-01 10:25 UTC, Janpot commented on test/integration/components/index.spec.ts
> +  await frame.locator('text="foo button"').waitFor({ state: 'visible' });
I'll assign those to variables with more descriptive names. That makes it self-documenting.

2023-02-01 17:18 UTC, apedroferreira commented on test/integration/components/index.spec.ts
> +  const optionsSelect = frame.getByRole('button', { name: /select with options/ });
Yeah that's right, with a page load in every test things can get a lot slower...
One test per component sounds like a good future-proof approach - we could also maybe slowly get rid of this general test as we create one test for each component.
I think the way you changed it is good!

2023-02-01 17:20 UTC, apedroferreira approved these changes

2023-02-01 17:20 UTC, merged