Docs-update
mui/mui-toolpad pull request #1829
Opened 2023-03-29 11:28 UTC by prakhargupta1

Data binding and deployment updates. Things to fix:
1. Deployment icon
2. Verify deployment content

- Closes 
- Visual demonstration 

<img width="1176" alt="Screenshot 2023-03-29 at 1 27 31 PM" src="https://user-images.githubusercontent.com/92228082/228521783-26914a1e-bcf2-41f4-ac39-e483c05a5310.png">

<img width="1154" alt="Screenshot 2023-03-29 at 1 27 14 PM" src="https://user-images.githubusercontent.com/92228082/228521741-26ec7e58-0101-4a87-b431-b7b592d0160f.png">

- Please follow the [the contributing guide on how to create great pull requests](https://github.com/mui/mui-toolpad/blob/master/CONTRIBUTING.md#sending-a-pull-request).

2023-03-29 11:40 UTC, prakhargupta1 commented
It would be great, if we can add a thin border on all of our images. Something like core docs also has:

<img width="816" alt="Screenshot 2023-03-29 at 1 38 44 PM" src="https://user-images.githubusercontent.com/92228082/228524200-5955ad9b-08bc-4986-8ff8-044c743f8041.png">

Or if there something better that someone might want to suggest.

2023-03-29 15:28 UTC, apedroferreira commented on docs/data/toolpad/data-binding.md
> +Components like MUI Button have onClick event handler props. This can be binded to run a piece of code to mutate the page state.
```suggestion
Some components, such as `Button`, have event handler props. Event handler props can be binded to run a piece of code to mutate the page state.
```

2023-03-29 15:29 UTC, apedroferreira commented on docs/data/toolpad/data-binding.md
> +(In the example below you can see how on Click of a button, the value is copied from one component to the other)
```suggestion
(In the example below you can see how after clicking the button, the value is copied from one component to the other)
```

2023-03-29 15:30 UTC, apedroferreira commented on docs/data/toolpad/deployment.md
> +<p class="description">Deploying a Toolpad app is a 3-step process and quite like any other react application.</p>
```suggestion
<p class="description">Deploying a Toolpad app is a 3-step process and quite like any other React application.</p>
```

2023-03-29 15:32 UTC, apedroferreira commented on docs/data/toolpad/deployment.md
> +Once the build has been made. You can deploy it to any service of your choice!
```suggestion
Once the build has been made, you can deploy it to any service of your choice!
```

2023-03-29 15:34 UTC, apedroferreira commented on docs/data/toolpad/deployment.md
> +This command will create an optimized production build for the Toolpad app and will output what files it has generated and how large each file is:
```suggestion
This command will create an optimized production build for the Toolpad app and will output the generated files:
```

2023-03-29 15:37 UTC, apedroferreira commented on docs/public/static/toolpad/docs/data-binding/bind-11.png
This image seems a bit small. 
Maybe we can have clearer "before" and "after" images so we can see how the binding changed things?

2023-03-29 15:38 UTC, apedroferreira commented
Deployment icon: maybe a rocket? :)

2023-03-29 15:39 UTC, apedroferreira commented
> It would be great, if we can add a thin border on all of our images. Something like core docs also has:
> 
> <img alt="Screenshot 2023-03-29 at 1 38 44 PM" width="816" src="https://user-images.githubusercontent.com/92228082/228524200-5955ad9b-08bc-4986-8ff8-044c743f8041.png">
> 
> Or if there something better that someone might want to suggest.

I think whatever Core does on their images we could do the same, since the docs look similar.
Let me know if I should look into it!

2023-03-29 15:40 UTC, apedroferreira requested changes
Nice one, Prakhar, just left some feedback and suggestions for copy changes!
All my opinion of course so feel free to disagree with any of them.

2023-03-29 17:30 UTC, apedroferreira commented
I've added a commit document `toolpad-display=standalone` since we will add it soon and there is a `Deployment` section in this PR where it feels appropriate.
I didn't include any images as maybe we should have a nice looking app to take screenshots from, and it didn't feel completely necessary in this case.

2023-04-05 02:07 UTC, bharatkashyap commented on docs/data/toolpad/data-binding.md
> +Components like MUI Button have onClick event handler props. This can be binded to run a piece of code to mutate the page state.
```suggestion
Some components have event handler props, such as the `Button` component and its `onClick` prop. Event handler props can be bound to run a piece of code to mutate the page state.
```

2023-04-05 02:08 UTC, bharatkashyap commented on docs/data/toolpad/deployment.md
> +<p class="description">Deploying a Toolpad app is a 3-step process and quite like any other react application.</p>
```suggestion
<p class="description">Deploying a Toolpad app is like deploying any other React application and has 3 steps:</p>
```

2023-04-06 06:28 UTC, prakhargupta1 commented on docs/public/static/toolpad/docs/data-binding/bind-11.png
In the pic above this one, I have tried to show the binding and in the background there is the before image. Hopefully, it should be ok.

2023-04-06 11:38 UTC, apedroferreira approved these changes

2023-04-06 11:51 UTC, prakhargupta1 commented
> Deployment icon: maybe a rocket? :)

That should be good! @apedroferreira Need your help in this. As per pages.ts it has something to do with mono repo docs.

2023-04-06 12:37 UTC, apedroferreira commented
> > Deployment icon: maybe a rocket? :)
> 
> That should be good! @apedroferreira Need your help in this. As per pages.ts it has something to do with mono repo docs.

Just changing the icon? I'll try it.

2023-04-06 13:08 UTC, prakhargupta1 commented
> Just changing the icon? I'll try it.

Yes

2023-04-06 14:39 UTC, apedroferreira commented
> > Just changing the icon? I'll try it.
> 
> Yes

My bad, looks like it's only possible to use icons from this file in those docs nav items https://github.com/mui/material-ui/blob/master/docs/src/modules/components/AppNavDrawerItem.js
So we can stick to the code one for now, but I can make a PR there to add the rocket icon, I guess I'll make a PR.

2023-04-10 14:20 UTC, merged