Changed MenuItem to ToggleButton (#2776)
mui/mui-toolpad pull request #2796
Opened 2023-10-12 19:18 UTC by biplobsd

I have changed MenuItem to ToggleButton as in the #2764 discussed.

- [x] I've read and followed the [contributing guide](https://github.com/mui/mui-toolpad/blob/master/CONTRIBUTING.md#sending-a-pull-request) on how to create great pull requests.
- [x] I've updated the relevant documentation for any new or updated feature.
- [x] I've linked relevant GitHub issue with "Closes #2776".
- [x] I've added a visual demonstration in the form of a screenshot or video.

## Screenshort
![image](https://github.com/mui/mui-toolpad/assets/43641536/0f76138c-973b-42db-bf4a-5bba3ffa14be)

2023-10-15 11:36 UTC, biplobsd commented
@apedroferreira Kindly take a review. Thanks

2023-10-16 19:15 UTC, apedroferreira requested changes
Awesome, thank you so much, it's perfect!

Before we can merge, can you just please:
1. Update the image in https://mui.com/toolpad/concepts/display-mode/
1. Run `yarn prettier:all` to fix the prettier errors
1. Fix the type error reported below in `test_types` too? We need to adjust the type for the `onChange` prop.

You can ignore the `test_unit` below, we will fix it. Thanks a lot!

2023-10-16 21:00 UTC, biplobsd commented
@apedroferreira Could you explain more the step 3. Is it in the CirecleCI `test_types` report?

2023-10-16 21:22 UTC, apedroferreira commented
> @apedroferreira Could you explain more the step 3. Is it in the CirecleCI `test_types` report?

Yes. that was it.
All good, now, thanks again!

2023-10-16 21:22 UTC, apedroferreira approved these changes

2023-10-16 21:26 UTC, apedroferreira commented on packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
> +    (event: React.MouseEvent<HTMLElement>, newValue: string) => {
```suggestion
    (event: React.MouseEvent<HTMLElement>, newValue: appDom.PageDisplayMode) => {
```

Just noticed I think we don't need to use `as`, we can just do this.

2023-10-16 21:26 UTC, apedroferreira commented on packages/toolpad-app/src/toolpad/AppEditor/PageEditor/PageOptionsPanel.tsx
> +          newValue as appDom.PageDisplayMode,
```suggestion
          newValue,
```

2023-10-17 15:58 UTC, merged

2023-10-19 03:08 UTC, biplobsd commented
@apedroferreira Can I get your Twitter handle? I want to tweet about this experience. 🙂

2023-10-19 16:50 UTC, apedroferreira commented
> @apedroferreira Can I get your Twitter handle? I want to tweet about this experience. 🙂

I don't have a Twitter, but feel free to do it, maybe you can tag MUI or something :)